### ISSUE TITLE
com.netflix.zuul.exception.ZuulException: Forwarding error

### ISSUE THREAD

**Issue by JadenDuan** [zhangqiang110/demo-spring-cloud#1]
您好：
我在使用zuul的时候出现了这样的错误，网上的解决办法是添加
```
ribbon:
  connect-timeout: 60000
  read-timeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

```
但是，idea提示我无法解析这三个字段，我看见您的在
additional-spring-configuration-metadata.json中配置了这三个字段，但是我在配置后仍然会出现forwarding error的问题，我不确定是否是因为我配置不生效导致的，您有什么建议吗？
